name: "ğŸ” Registry Recovery"

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  retry:
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸšš Checkout"
        uses: actions/checkout@v4

      - name: "ğŸ”„ Process Recovery"
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./scripts/recovery_manager.js');
            await script({github, context, core});
